# Generated by Django 6.0.3 on 2026-03-27 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='add_students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_Name', models.CharField(max_length=30)),
                ('Dob', models.DateField()),
                ('Class', models.CharField()),
                ('Parent_Contact', models.IntegerField(max_length=10)),
                ('Gender', models.CharField()),
                ('Email', models.EmailField(max_length=254)),
                ('Address', models.CharField(max_length=80)),
            ],
        ),
        migrations.DeleteModel(
            name='add_student',
        ),
    ]
