# Generated by Django 6.0.3 on 2026-03-27 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0003_alter_add_students_parent_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='add_teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_Name', models.CharField(max_length=30)),
                ('Gender', models.CharField()),
                ('Dob', models.DateField()),
                ('Email', models.EmailField(max_length=254)),
                ('Phone', models.IntegerField()),
                ('Subject', models.CharField(max_length=15)),
                ('Experience', models.CharField(max_length=15)),
                ('Join_Date', models.DateField()),
                ('Address', models.CharField(max_length=50)),
            ],
        ),
    ]
