# Generated by Django 6.0.3 on 2026-03-27 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0004_add_teachers'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_teachers',
            name='Qualifications',
            field=models.CharField(default='NA'),
            preserve_default=False,
        ),
    ]
