# Generated by Django 6.0.3 on 2026-03-27 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0002_add_students_delete_add_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_students',
            name='Parent_Contact',
            field=models.IntegerField(),
        ),
    ]
