# Generated by Django 6.0.3 on 2026-03-25 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('contact', models.IntegerField()),
            ],
        ),
    ]
